### Make category
POST http://localhost:8080/categoriesPost
Content-Type: application/json

{
"name": "Food1",
"type": "expense4"
}

### get all categories
GET http://localhost:8080/categories

### Make a transaction
POST http://localhost:8080/transactions
Content-Type: application/json

{
  "amount": 29.99,
  "date": "2023-10-15",
  "description": "Grocery shopping",
  "type": "expense",
  "categoryId": 1
}
### Get transactions
GET http://localhost:8080/transactions
### Delete trans
DELETE http://localhost:8080/transactions/2

### Get summary
GET /summary?timeRange=monthly

### Update transacion
PUT http://localhost:8080/transactions/1
Content-Type: application/json

{
  "amount": 100,
  "date": "2025-05-28",
  "description": "Updated Nintendo Game",
  "type": "expense",
  "categoryId": 1
}